name: Run sanitycheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Clone ${{ github.repository }}
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.name }}

    - name: Clone dlang-tour/core
      uses: actions/checkout@v3
      with:
        repository: dlang-tour/core
        path: core

    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Run sanitycheck'
      run: |
        dub --root=core --compiler=${DC} -- --sanitycheck --lang-dir=./${{ github.event.repository.name }}
